//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrolleyTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trolley
    {
        public int ID { get; set; }
        public string TrolleyName { get; set; }
        public int Number { get; set; }
        public Nullable<double> CurrentLat { get; set; }
        public Nullable<double> CurrentLon { get; set; }
    }
}
